### ISSUE TITLE
BAPL crashes on Devices running Fire TV OS 7 issue. Some users have also reported the issue on Fire TV Cube.

### ISSUE THREAD

**Issue by visnkmr** [visnkmr/backgroundappslist#1]
```
: I/ActivityManager(3337): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:troubleshoot.bapl flg=0x4000000 cmp=com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity} from uid 10199
: I/DolbyAudioHwDeviceProxy(3101): resumeDownstream() for device:0x400
: D/AudioFlinger(3108): mixer(0xe9c83b80) throttle end: throttle time(8)
: E/FirebaseInstanceId(10452): Google Play services missing or without correct permission.
: W/ActivityThread(11736): handleWindowVisibility: no activity for token android.os.BinderProxy@bc1cf10
: D/DolbyAudioHwDeviceProxy(3101): setParameters(audio_hw_if): continuous_audio_mode=0
: I/AudioALSAHardware(3101): +setParameters(): continuous_audio_mode=0
: W/AudioALSAHardware(3101): setParameters(), still have param.size() = 1, remain param = "continuous_audio_mode=0"
: D/AudioALSAHardware(3101): -setParameters(): continuous_audio_mode=0 
: I/Vizzini_2.0.3491.0:ExternalPlaybackStateManager(3911): Media State Update: CODEC_STATE_DETECTION is INACTIVE
: I/Vizzini_2.0.3491.0:ExternalPlaybackStateManager(3911): MediaStatus inactive or no media states to get context from.
: I/Vizzini_2.0.3491.0:ExternalPlaybackStateManager(3911): No active media, removing LocalMediaPlayerStateContext
: I/Vizzini_2.0.3491.0:AlexaContextClient(3911): Removing device context namespace: LocalMediaPlayer, name: PlaybackState
: D/DolbyAudioHwDeviceProxy(3101): setParameters(audio_hw_if): continuous_audio_mode=0
: I/SPCH-SIM_SimDeviceContextContract(3911): removeDeviceContext(LocalMediaPlayer, PlaybackState)
: D/DolbyAudioHwDeviceProxy(3108): setParameters(audio_hw_if): continuous_audio_mode=0
: D/DolbyAudioHwDeviceProxy(3101): getParameters(audio_hw_if): hdmi_output_channel_mode
: I/DolbyAudioParameters(3101): getParameters() return hdmi_output_channel_mode=0
: D/DolbyAudioHwDeviceProxy(3101): getParameters(audio_hw_if): hdmi_output_channel_mode
: I/DolbyAudioParameters(3101): getParameters() return hdmi_output_channel_mode=0
: E/SELinux(3337): avc:  denied  { log_internal_metric } for  scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:r:system_server:s0 tclass=amazon_policies permissive=0
: D/DolbyAudioHwDeviceProxy(3108): getParameters(audio_hw_if): hdmi_output_channel_mode;
: I/DolbyAudioParameters(3108): getParameters() return hdmi_output_channel_mode=0
: I/Vizzini_2.0.3491.0:ExternalPlaybackStateManager(3911): Focus already cleared
: I/SPCH-SIM_SimStateMachine(3911): Got DeviceContextEvent in ReadyState
: I/BaseContextManager(3911): Removing device context = [namespace=LocalMediaPlayer, name=PlaybackState]
: V/MouseModeService(3337): packageName=com.amazon.tv.settings.v2 activityName= mouseModeEnabled=false
: I/AVL:AVLManagerService(5813): Setting package name: *****
: I/Vizzini_2.0.3491.0:ExternalPlaybackStateManager(3911): Focus already cleared
: D/AlexaFocusChannelSet(3911): Target (com.amazon.tv.settings.v2) has not reported an active namespace
: I/AVL:AVLManagerService(5813): handling : 0
: I/AVL:ManifestMetadata(5813): Manifest metadata queried for package :*****
: I/AVL:AVLManagerService(5813): App certification whitelist status : false
: I/SPCH-SIM_SimStateMachine(3911): Got FocusEvent in ReadyState
: D/AlexaFocusContract(3911): releaseFocus namespace (AlexaVoiceLayer) channel (inFocus) package (com.amazon.avl.stark)
: D/AlexaFocusChannelSet(3911): releaseFocus namespace (AlexaVoiceLayer) channel (inFocus) client (com.amazon.avl.stark) type (Binder)
: D/AlexaFocusFilter(3911): Namespace (AlexaVoiceLayer) accepted as Local Application interface
: D/AlexaFocusInFocusChannel(3911): releaseFocus namespace (AlexaVoiceLayer) packageName (com.amazon.avl.stark) client (android.os.BinderProxy@a968845)
: D/AlexaFocusContract(3911): Could not release focus for namespace (AlexaVoiceLayer) channel (inFocus) package (com.amazon.avl.stark)
: D/AlexaFocusChannelSet(3911): Target (com.amazon.tv.settings.v2) does not support any namespaces
: W/AlexaFocusVisualChannelSet(3911): Package (com.amazon.tv.settings.v2) has not registered a namespace; attempting clear
: D/AudioFlinger(3108): mixer(0xe9c83b80) throttle end: throttle time(16)
: I/PointerController(3337): PointerController setInvisible true
: I/SPCH-SIM_SimStateMachine(3911): Got DeviceContextEvent in ReadyState
: I/SPCH-SIM_SimStateMachine(3911): Got CapabilityCheckEvent in ReadyState
: I/DolbyAudioStreamOut(3101): getLatency() Total latency:285ms (Downstream:73ms, DMA:142ms, tuning:70ms, tuningBT:0ms), input format:0x1, sink:0x400, UxOutSetting:0, CurOutFormat:0xa000000
: D/WakeWordService(3927): event audio_playback with value 1 and decoderId WakeWordService_input_decoder has been pushed into Pryon
: I/gralloc(3087): framebuffer hal alread move to hwcomposer
: I/DolbyAudioStreamOut(3101): getLatency() Total latency:296ms (Downstream:84ms, DMA:142ms, tuning:70ms, tuningBT:0ms), input format:0x1, sink:0x400, UxOutSetting:0, CurOutFormat:0xa000000
: I/gralloc(3087): framebuffer hal alread move to hwcomposer
: I/gralloc(3087): framebuffer hal alread move to hwcomposer
: I/DolbyAudioStreamOut(3101): getLatency() Total latency:289ms (Downstream:77ms, DMA:142ms, tuning:70ms, tuningBT:0ms), input format:0x1, sink:0x400, UxOutSetting:0, CurOutFormat:0xa000000
: D/mali_winsys(10452): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
: E/FirebaseInstanceId(10452): Google Play services missing or without correct permission.
: I/AmazonPowerManagerVendorCallback(3337): Wakelock acquired UID:1000 PID:3337 Tag:WindowManager
: I/...s.v2/PlatformWrapper(11736): MAP support direct boot aware on current platform: true
: I/...s.v2/PlatformWrapper(11736): MAP is in direct boot mode: false
: E/ST-ApplicationsAct(11736): SSO setting not found! settings_sso_visibility
: I/...s.v2/PlatformWrapper(11736): MAP support direct boot aware on current platform: true
: I/...s.v2/PlatformWrapper(11736): MAP is in direct boot mode: false
: I/DolbyAudioStreamOut(3101): getLatency() Total latency:292ms (Downstream:80ms, DMA:142ms, tuning:70ms, tuningBT:0ms), input format:0x1, sink:0x400, UxOutSetting:0, CurOutFormat:0xa000000
: D/AndroidRuntime(11736): Shutting down VM
: E/AndroidRuntime(11736): FATAL EXCEPTION: main
: E/AndroidRuntime(11736): Process: com.amazon.tv.settings.v2, PID: 11736
: E/AndroidRuntime(11736): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.amazon.tv.leanback.widget.VerticalGridView.getSelectedPosition()' on a null object reference
: E/AndroidRuntime(11736): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
: E/AndroidRuntime(11736): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3069)
: E/AndroidRuntime(11736): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
: E/AndroidRuntime(11736): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
: E/AndroidRuntime(11736): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
: E/AndroidRuntime(11736): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
: E/AndroidRuntime(11736): 	at android.os.Handler.dispatchMessage(Handler.java:106)
: E/AndroidRuntime(11736): 	at android.os.Looper.loop(Looper.java:193)
: E/AndroidRuntime(11736): 	at android.app.ActivityThread.main(ActivityThread.java:6734)
: E/AndroidRuntime(11736): 	at java.lang.reflect.Method.invoke(Native Method)
: E/AndroidRuntime(11736): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
: E/AndroidRuntime(11736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
: E/AndroidRuntime(11736): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.amazon.tv.leanback.widget.VerticalGridView.getSelectedPosition()' on a null object reference
: E/AndroidRuntime(11736): 	at com.amazon.tv.settingslib.SettingsLayoutFragment.refreshDetailsPane(SettingsLayoutFragment.java:927)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity$12.onFinishedMeasuringApps(ApplicationsActivity.java:1224)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settings.v2.tv.applications.StorageStatsApplicationSizeComputer.measureApplications(StorageStatsApplicationSizeComputer.java:71)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity.measureAppSizeBackground(ApplicationsActivity.java:844)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity.access$2800(ApplicationsActivity.java:97)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity$15.get(ApplicationsActivity.java:1208)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settingslib.Layout.addNodeListToLayoutRows(Layout.java:3200)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settingslib.Layout.updateLayoutRows(Layout.java:3239)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settingslib.SettingsLayoutActivity.onCreate(SettingsLayoutActivity.java:9007)
: E/AndroidRuntime(11736): 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity.onCreate(ApplicationsActivity.java:315)
: E/AndroidRuntime(11736): 	at android.app.Activity.performCreate(Activity.java:7151)
: E/AndroidRuntime(11736): 	at android.app.Activity.performCreate(Activity.java:7141)
: E/AndroidRuntime(11736): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
: E/AndroidRuntime(11736): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
: E/AndroidRuntime(11736): 	... 11 more
: W/ActivityManager(3337):   Force finishing activity com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity
: W/ActivityManager(3337):   Force finishing activity com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity
: I/CrashReporterActivityManagerCallback(3337): addErrorToDropBox inserted hashcode=39c9964d0094afe6b95e0261ae8e6391fe7df635 for eventType crash.
: W/ActivityManager(3337):   Force finishing activity troubleshoot.bapl/.MainActivity
: I/Process(11736): Sending signal. PID: 11736 SIG: 9
: I/DolbyAudioStreamOut(3101): getLatency() Total latency:296ms (Downstream:84ms, DMA:142ms, tuning:70ms, tuningBT:0ms), input format:0x1, sink:0x400, UxOutSetting:0, CurOutFormat:0xa000000
: Observed consecutive frames of digital silence: 427
: W/InputDispatcher(3337): channel 'f2d9960 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
: E/InputDispatcher(3337): channel 'f2d9960 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
: E/AmazonHdmiService(3337): Settings client binder died.
: I/ActivityManager(3337): Process com.amazon.tv.settings.v2 (pid 11736) has died: fore TOP 
: W/libprocessgroup(3337): kill(-11736, 9) failed: No such process
: I/WindowManager(3337): WIN DEATH: Window{f2d9960 u0 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity}
: W/InputDispatcher(3337): Attempted to unregister already unregistered input channel 'f2d9960 com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity (server)'
: I/Zygote(3047): Process 11736 exited due to signal (9)
: W/Eve(3337): MEMORY_LEVEL: [11736,0]
: W/Eve(3337):   top=com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity launching=true
: W/Eve(3337):   prev=troubleshoot.bapl/.MainActivity screen_on=true thermal=0
: W/Eve(3337):   adb=true downloading=false
: W/Eve(3337):   memory=0 available=0KB free=303892KB
: W/Eve(3337): Lmk did not kill com.amazon.tv.settings.v2
: W/EveThread(3337): type=1400 audit(0.0:391): avc: denied { read } for name="lmk_logs" dev="proc" ino=4026532103 scontext=u:r:system_server:s0 tcontext=u:object_r:proc:s0 tclass=file permissive=0
```

**Comment by visnkmr** [comment]
**The issue lies in the following lines which seem to be an issue with the setting app on Fire TVs running OS 7 wherein the settings app recognises apps based on their number in the list of allapps but the android api usually works by opening app settings screen based on package name provided by developer.**



```
Shutting down VM
 FATAL EXCEPTION: main

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazon.tv.settings.v2/com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.amazon.tv.leanback.widget.VerticalGridView.getSelectedPosition()' on a null object reference
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3069)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loop(Looper.java:193)
 	at android.app.ActivityThread.main(ActivityThread.java:6734)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.amazon.tv.leanback.widget.VerticalGridView.getSelectedPosition()' on a null object reference
 	at com.amazon.tv.settingslib.SettingsLayoutFragment.refreshDetailsPane(SettingsLayoutFragment.java:927)
 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity$12.onFinishedMeasuringApps(ApplicationsActivity.java:1224)
 	at com.amazon.tv.settings.v2.tv.applications.StorageStatsApplicationSizeComputer.measureApplications(StorageStatsApplicationSizeComputer.java:71)
 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity.measureAppSizeBackground(ApplicationsActivity.java:844)
 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity.access$2800(ApplicationsActivity.java:97)
 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity$15.get(ApplicationsActivity.java:1208)
 	at com.amazon.tv.settingslib.Layout.addNodeListToLayoutRows(Layout.java:3200)
 	at com.amazon.tv.settingslib.Layout.updateLayoutRows(Layout.java:3239)
 	at com.amazon.tv.settingslib.SettingsLayoutActivity.onCreate(SettingsLayoutActivity.java:9007)
 	at com.amazon.tv.settings.v2.tv.applications.ApplicationsActivity.onCreate(ApplicationsActivity.java:315)
 	at android.app.Activity.performCreate(Activity.java:7151)
 	at android.app.Activity.performCreate(Activity.java:7141)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
 	... 11 more
: W/ActivityManager(3337   Force finishing activity com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity
: W/ActivityManager(3337   Force finishing activity com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity
: I/CrashReporterActivityManagerCallback(3337 addErrorToDropBox inserted hashcode=39c9964d0094afe6b95e0261ae8e6391fe7df635 for eventType crash.
: W/ActivityManager(3337   Force finishing activity troubleshoot.bapl/.MainActivity
```

**Comment by visnkmr** [comment]
Update: This issue has been fixed; This was probably fixed in a Fire OS update in Jan or February 2021.
